SET TERM ^ ;

CREATE OR ALTER PROCEDURE ADD_SYS_COLUMN_2 (
  FIELD    TSTRING,
  LABEL    TSTRING
  )
RETURNS (
  ID TINTEGER
  )
AS
BEGIN

  SELECT FIRST 1 ID
  FROM SYS_COLUMN
  WHERE FIELD = :FIELD
    AND LABEL = :LABEL
    AND TITLE = ''
  INTO :ID;

  IF (COALESCE(:ID, 0) = 0) THEN
    INSERT INTO SYS_COLUMN (ID, FIELD, TITLE, LABEL, CHECKBOX)
    VALUES (UDF_GUID_SHA(), :FIELD, '', :LABEL, 0)
    RETURNING ID INTO :ID;

   SUSPEND;
END^

SET TERM ; ^

