SET TERM ^;

CREATE OR ALTER PROCEDURE ADD_SYS_GRID_EDIT(
   ID_GRID    TINTEGER
  ,SORT_ORDER TINTEGER
  ,FIELD      TSTRING
  ,TITLE      TSTRING
  ,LABEL      TSTRING
  ,CHECKBOX   TBOOLEAN2
  ,CONTROL_TYPE       TSTRING
  ,FIELD_WIDTH        TINTEGER
  ,FIELD_HEIGHT       TINTEGER
  ,FIELD_NEWL         TBOOLEAN2
  ,FIELD_NEWT         TBOOLEAN2
  ,REQUIRED           TBOOLEAN2
  ,CLONE_ABLE         TBOOLEAN2
  ,LOOKUP_FIELD_VALUE TSTRING = ''
  ,LOOKUP_LIST_KEY    TSTRING = ''
  ,LOOKUP_LIST_VALUE  TSTRING = ''
  ,LOOKUP_IID         TSTRING = ''
  ,LOOKUP_SQL         TSTRING = ''
  ,LOOKUP_SQL_NAME    TSTRING = ''
  ,LOOKUP_SQL_MASTER  TSTRING = ''
)
AS
  DECLARE ID_COLUMN TYPE OF TINTEGER;
BEGIN
  SELECT ID FROM ADD_SYS_COLUMN(:FIELD,:TITLE,:LABEL,:CHECKBOX) INTO :ID_COLUMN;

  IF (:LOOKUP_SQL_NAME = '') THEN
    LOOKUP_SQL_NAME = :LOOKUP_SQL;

  IF (NOT EXISTS(SELECT 1 FROM SYS_GRID_EDIT WHERE ID_GRID = :ID_GRID AND ID_COLUMN = :ID_COLUMN)) THEN
    INSERT INTO SYS_GRID_EDIT (
      ID_GRID,ID_COLUMN,SORT_ORDER,CONTROL_TYPE,FIELD_WIDTH,FIELD_HEIGHT,FIELD_NEWL,FIELD_NEWT,
      LOOKUP_FIELD_VALUE,LOOKUP_LIST_KEY,LOOKUP_LIST_VALUE,
      LOOKUP_IID,LOOKUP_SQL,LOOKUP_SQL_NAME,LOOKUP_SQL_MASTER,CLONE_ABLE,REQUIRED)
    VALUES (
      :ID_GRID,:ID_COLUMN,:SORT_ORDER,:CONTROL_TYPE,:FIELD_WIDTH,:FIELD_HEIGHT,:FIELD_NEWL,:FIELD_NEWT,
      :LOOKUP_FIELD_VALUE,:LOOKUP_LIST_KEY,:LOOKUP_LIST_VALUE,
      :LOOKUP_IID,:LOOKUP_SQL,:LOOKUP_SQL_NAME,:LOOKUP_SQL_MASTER,:CLONE_ABLE,:REQUIRED);
  ELSE
    UPDATE SYS_GRID_EDIT SET
       SORT_ORDER         = :SORT_ORDER
      ,CONTROL_TYPE       = :CONTROL_TYPE
      ,FIELD_WIDTH        = :FIELD_WIDTH
      ,FIELD_HEIGHT       = :FIELD_HEIGHT
      ,FIELD_NEWL         = :FIELD_NEWL
      ,FIELD_NEWT         = :FIELD_NEWT
      ,LOOKUP_FIELD_VALUE = :LOOKUP_FIELD_VALUE
      ,LOOKUP_LIST_KEY    = :LOOKUP_LIST_KEY
      ,LOOKUP_LIST_VALUE  = :LOOKUP_LIST_VALUE
      ,LOOKUP_IID         = :LOOKUP_IID
      ,LOOKUP_SQL         = :LOOKUP_SQL
      ,LOOKUP_SQL_NAME    = :LOOKUP_SQL_NAME
      ,LOOKUP_SQL_MASTER  = :LOOKUP_SQL_MASTER
      ,CLONE_ABLE         = :CLONE_ABLE
      ,REQUIRED           = :REQUIRED
    WHERE ID_GRID   = :ID_GRID
      AND ID_COLUMN = :ID_COLUMN;

END
^

SET TERM ;^
