SET TERM ^;

CREATE OR ALTER PROCEDURE AP_PHOTO_DECISION$GET(
   A_ID TINTEGER
  )
RETURNS (
   ID                TINTEGER
  ,ID_APP            TINTEGER
  ,NUMBER            TSTRING
  ,PHOTO             TBINARY
  ,DECISION_DATE     TDATETIME
  ,INSPECTOR_NAME    TSTRING
  ,OVS_CODE          TSTRING
  ,OVS_NAME          TSTRING
  ,VIOLATION_DATE    TDATETIME
  ,VIOLATION_PLACE   TSTRING
  ,MARK              TSTRING
  ,MODEL             TSTRING
  ,DNZ_NUMBER        TSTRING
  ,LAST_NAME         TSTRING
  ,FIRST_NAME        TSTRING
  ,MIDDLE_NAME       TSTRING
  ,PASS_NO           TSTRING
  ,BIRTHDAY          TDATE
  ,BIRTH_PLACE       TSTRING
  ,REGION_NAME       TSTRING
  ,STREET_NAME       TSTRING
  ,HOUSE_NO          TSTRING
  ,BUILDING_NO       TSTRING
  ,FLAT_NO           TSTRING
  ,TRAFFIC_SIGN      TSTRING
  ,ROADRULE_NO       TSTRING
  ,ARTICLE_NO        TSTRING
  ,LIMIT_SPEED       TINTEGER
  ,ACTUAL_SPEED      TINTEGER
  ,PENALTY           TMONEY
  ,BREACH_ID         TSTRING
  ,DEVICE_NAME       TSTRING
  ,DEVICE_NO         TSTRING
  ,DEVICE_VALID_DATE TDATE
  ,BANK_MFO          TSTRING
  ,BANK_ACCOUNT      TSTRING
  ,RECIPIENT_OKPO    TSTRING
  ,RECIPIENT_NAME    TSTRING
  )
AS
  DECLARE V_SQL TTEXT;
BEGIN

  SELECT
     D.ID
    ,D.ID_APP
    ,D.NUMBER
    ,D.PHOTO
    ,D.DECISION_DATE
    ,D.INSPECTOR_ID
    ,D.OVS_CODE
    ,O.NAME
    ,D.VIOLATION_DATE
    ,D.VIOLATION_PLACE
    ,D.MARK
    ,D.MODEL
    ,D.DNZ_NUMBER
    ,D.LAST_NAME
    ,D.FIRST_NAME
    ,D.MIDDLE_NAME
    ,D.PASS_NO
    ,D.BIRTHDAY
    ,D.BIRTH_PLACE
    ,D.REGION_ID
    ,D.STREET_NAME
    ,D.HOUSE_NO
    ,D.BUILDING_NO
    ,D.FLAT_NO
    ,D.TRAFFIC_SIGN
    ,D.ROADRULE_NO
    ,D.ARTICLE_NO
    ,D.LIMIT_SPEED
    ,D.ACTUAL_SPEED
    ,D.PENALTY
    ,D.BREACH_ID
    ,D.DEVICE_NAME
    ,D.DEVICE_NO
    ,D.DEVICE_VALID_DATE
    ,D.BANK_MFO
    ,D.BANK_ACCOUNT
    ,D.RECIPIENT_OKPO
    ,D.RECIPIENT_NAME
  FROM AP_PHOTO_DECISION D
    JOIN C_OVS O ON D.OVS_CODE = O.CODE
  WHERE D.ID = :A_ID
  INTO
     :ID
    ,:ID_APP
    ,:NUMBER
    ,:PHOTO
    ,:DECISION_DATE
    ,:INSPECTOR_NAME
    ,:OVS_CODE
    ,:OVS_NAME
    ,:VIOLATION_DATE
    ,:VIOLATION_PLACE
    ,:MARK
    ,:MODEL
    ,:DNZ_NUMBER
    ,:LAST_NAME
    ,:FIRST_NAME
    ,:MIDDLE_NAME
    ,:PASS_NO
    ,:BIRTHDAY
    ,:BIRTH_PLACE
    ,:REGION_NAME
    ,:STREET_NAME
    ,:HOUSE_NO
    ,:BUILDING_NO
    ,:FLAT_NO
    ,:TRAFFIC_SIGN
    ,:ROADRULE_NO
    ,:ARTICLE_NO
    ,:LIMIT_SPEED
    ,:ACTUAL_SPEED
    ,:PENALTY
    ,:BREACH_ID
    ,:DEVICE_NAME
    ,:DEVICE_NO
    ,:DEVICE_VALID_DATE
    ,:BANK_MFO
    ,:BANK_ACCOUNT
    ,:RECIPIENT_OKPO
    ,:RECIPIENT_NAME;

  SUSPEND;

END^

SET TERM ;^
