SET TERM ^;

CREATE OR ALTER PROCEDURE SYS_SET_PRIVILEGES
AS
  DECLARE VARIABLE V_NAME TSTRING;
BEGIN
  FOR
    SELECT RDB$RELATION_NAME FROM RDB$RELATIONS WHERE COALESCE(RDB$SYSTEM_FLAG, 1) <> 1
    INTO :V_NAME
  DO
    EXECUTE STATEMENT 'GRANT ALL ON TABLE '||TRIM(:V_NAME)||' TO PUBLIC';

  FOR
    SELECT RDB$PROCEDURE_NAME FROM RDB$PROCEDURES WHERE COALESCE(RDB$SYSTEM_FLAG, 1) <> 1
    INTO :V_NAME
  DO
    EXECUTE STATEMENT 'GRANT EXECUTE ON PROCEDURE '||TRIM(:V_NAME)||' TO PUBLIC';
END
^

SET TERM ;^

COMMENT ON PROCEDURE SYS_SET_PRIVILEGES IS 
'Устанавливает все права для всех. Необходима для автоматической расдачи прав для всех на новые метаданные. На настоящее время мы не геммороимся с системой прав доступа к базе данных.';

