SET TERM ^;

CREATE OR ALTER PROCEDURE SYS_STATE_TRIGGER (
    A_TRIGGER TSTRING,
    A_STATE TSTRING,
    A_CHECK_EXISTING TBOOLEAN = 1)
AS
  DECLARE V_STATE    VARCHAR(31);
  DECLARE V_TRIGGER  VARCHAR(31);
BEGIN
  V_TRIGGER = UPPER(TRIM(:A_TRIGGER));
  V_STATE = UPPER(TRIM(:A_STATE));

  IF (NOT (:V_STATE = 'INACTIVE' OR :V_STATE = 'ACTIVE')) THEN
    EXCEPTION EX_CUSTOM :V_STATE||' IS NOT INACTIVE OR ACTIVE';

  IF (NOT EXISTS (SELECT T.RDB$TRIGGER_NAME FROM RDB$TRIGGERS T WHERE T.RDB$TRIGGER_NAME = :V_TRIGGER)) THEN
    IF (A_CHECK_EXISTING = 1) THEN
      EXCEPTION EX_CUSTOM :V_TRIGGER||' IS NOT EXISTS';
    ELSE
      EXIT;

  EXECUTE STATEMENT 'ALTER TRIGGER '||:V_TRIGGER||' '||:V_STATE||'';
END
^

SET TERM ;^

COMMENT ON PROCEDURE SYS_STATE_TRIGGER IS 
'Переключение статус конкретного триггера с возможностью отключения проверки его существования.';

