SET TERM ^;

CREATE OR ALTER PROCEDURE TR_APPLICATIONS$CREATE(
   DNZ_NUMBER  TSTRING
  ,MARK        TSTRING
  ,MODEL       TSTRING
  ,LAST_NAME   TSTRING
  ,FIRST_NAME  TSTRING
  ,MIDDLE_NAME TSTRING
  ,PASS_NO     TSTRING
  ,BIRTHDAY    TDATETIME
  ,BIRTH_PLACE TSTRING
  ,REGION_ID   TSTRING
  ,STREET_NAME TSTRING
  ,HOUSE_NO    TSTRING
  ,BUILDING_NO TSTRING
  ,FLAT_NO     TSTRING
  )
AS
BEGIN
  INSERT INTO TR_APPLICATIONS (
     ID
    ,APP_NUMBER
    ,APP_DATE
    ,MARK
    ,MODEL
    ,DNZ_NUMBER
    ,LAST_NAME
    ,FIRST_NAME
    ,MIDDLE_NAME
    ,PASS_NO
    ,BIRTHDAY
    ,BIRTH_PLACE
    ,REGION_ID
    ,STREET_NAME
    ,HOUSE_NO
    ,BUILDING_NO
    ,FLAT_NO
  ) VALUES (
     UDF_GUID_SHA()
    ,:DNZ_NUMBER
    ,CURRENT_TIMESTAMP
    ,:MARK
    ,:MODEL
    ,:DNZ_NUMBER
    ,:LAST_NAME
    ,:FIRST_NAME
    ,:MIDDLE_NAME
    ,:PASS_NO
    ,:BIRTHDAY
    ,:BIRTH_PLACE
    ,:REGION_ID
    ,:STREET_NAME
    ,:HOUSE_NO
    ,:BUILDING_NO
    ,:FLAT_NO
  );

END^

SET TERM ;^
