INSERT INTO SYS_VER(ID) VALUES(%VERSION%);

ROLLBACK;

INPUT '..\sql-mdo\%VERSION_FOLDER%\update_body.sql';

COMMIT;

-- set version
INSERT INTO SYS_VER(ID) VALUES(%VERSION%);

COMMIT;

EXECUTE PROCEDURE SYS_SET_PRIVILEGES;
EXECUTE PROCEDURE SYS_SET_STATISTICS;

COMMIT;
