--------------------
-- DOMAINs
--------------------

CREATE DOMAIN TSTRING4K   AS VARCHAR(4096) CHARACTER SET WIN1251 DEFAULT '' NOT NULL COLLATE WIN1251_UA;
CREATE DOMAIN TSTRINGLONG AS VARCHAR(1024) CHARACTER SET WIN1251 DEFAULT '' NOT NULL COLLATE WIN1251_UA;
COMMIT;

COMMENT ON DOMAIN TSTRING4K IS 'varchar(4096) win1251_ua not null ''''';
COMMENT ON DOMAIN TSTRINGLONG IS 'Домен для длинных строк. Все что больше - уже блобы.';
COMMENT ON DOMAIN TTEXT IS 'Домен для больших текстовых';
COMMIT;
CREATE TABLE AP_PHOTO_FOLDER (
    ID           TSTRING,
    FOLDER       TSTRING,
    ADRESS       TSTRING,
    DEVICE_NAME  TSTRING,
    DEVICE_CODE  TSTRING,
    DEVICE_DATE  TDATETIME
);
COMMIT;

ALTER TABLE AP_PHOTO_FOLDER ADD CONSTRAINT AP_PHOTO_FOLDER$ID PRIMARY KEY (ID);
COMMIT;

--------------------
-- UDFs
--------------------

DECLARE EXTERNAL FUNCTION UDF_GUID_SHA RETURNS BIGINT BY VALUE ENTRY_POINT 'UDF_GUID_SHA' MODULE_NAME 'mdo_udfs';
COMMIT;
COMMENT ON EXTERNAL FUNCTION UDF_GUID_SHA IS 'Функция получения GUID в целочисленном виде (квазихеширование алгоритмом SHA-1)';
COMMIT;

--------------------
-- EXCEPTIONs
--------------------

CREATE EXCEPTION EX_CUSTOM 'ЭТОТ ТЕКСТ СООБЩЕНИЯ ДОЛЖЕН БЫТЬ ПЕРЕОПРЕДЕЛЕН РАЗРАБОТЧИКОМ.';

--------------------
-- SYS_LANG_RESOURCE
--------------------

CREATE TABLE SYS_LANG_RESOURCE (
  ID        TPRIMARY,
  NAME_KEY  TSTRING,
  VALUE_UA  TSTRING4K,
  VALUE_RU  TSTRING4K,
  VALUE_EN  TSTRING4K,
  USER_TIME TDATETIME,
  VALUE_CUR COMPUTED BY (VALUE_RU)
);
COMMIT;

ALTER TABLE SYS_LANG_RESOURCE ADD CONSTRAINT SYS_LANG_RESOURCE$ID PRIMARY KEY (ID);
CREATE INDEX SYS_LANG_RESOURCE$KEY ON SYS_LANG_RESOURCE COMPUTED BY (UPPER(NAME_KEY));

COMMIT;

-----------
-- SYS_GRID
-----------

CREATE TABLE SYS_GRID (
    ID    TPRIMARY,
    IID   TSTRING,
    NAME  TSTRING
);
COMMIT;

ALTER TABLE SYS_GRID ADD CONSTRAINT SYS_GRID$ID PRIMARY KEY (ID);
CREATE UNIQUE INDEX SYS_GRID$IID ON SYS_GRID (IID);
COMMIT;

COMMENT ON TABLE SYS_GRID IS 'Справочник гридов для системы автоматической настройки колонок';
COMMENT ON COLUMN SYS_GRID.IID  IS 'GUID грида. Константой прописана на клиенте';
COMMENT ON COLUMN SYS_GRID.NAME IS 'Наименование грида';
COMMIT;

-------------
-- SYS_COLUMN
-------------

CREATE TABLE SYS_COLUMN (
    ID        TPRIMARY,
    FIELD     TSTRING,
    TITLE     TSTRING,
    LABEL     TSTRING,
    CHECKBOX  TBOOLEAN2
);
COMMIT;

ALTER TABLE SYS_COLUMN ADD CONSTRAINT SYS_COLUMN$ID PRIMARY KEY (ID);
COMMIT;

COMMENT ON TABLE SYS_COLUMN IS 'Справочник колонок для системы автоматической настройки колонок';
COMMENT ON COLUMN SYS_COLUMN.FIELD IS 'Наименование поля';
COMMENT ON COLUMN SYS_COLUMN.TITLE IS 'Заголовок группы колонок';
COMMENT ON COLUMN SYS_COLUMN.LABEL IS 'Заголовок колоноки';
COMMENT ON COLUMN SYS_COLUMN.CHECKBOX IS 'Отображать значение как чекбокс';
COMMIT;

------------------
-- SYS_GRID_COLUMN
------------------

CREATE TABLE SYS_GRID_COLUMN (
    ID_GRID     TFOREIGN,
    ID_COLUMN   TFOREIGN,
    SORT_ORDER  TINTEGER,
    WIDTH       TINTEGER,
    VISIBLE     TBOOLEAN2,
    FOOT_FNC    TENUM
);
COMMIT;

ALTER TABLE SYS_GRID_COLUMN ADD CONSTRAINT SYS_GRID_COLUMN$ID_COLUMN FOREIGN KEY (ID_COLUMN) REFERENCES SYS_COLUMN (ID) ON DELETE CASCADE;
ALTER TABLE SYS_GRID_COLUMN ADD CONSTRAINT SYS_GRID_COLUMN$ID_GRID FOREIGN KEY (ID_GRID) REFERENCES SYS_GRID (ID) ON DELETE CASCADE;
COMMIT;

COMMENT ON TABLE SYS_GRID_COLUMN IS 'Связка гридов и колонок для системы автоматической настройки колонок';
COMMENT ON COLUMN SYS_GRID_COLUMN.ID_GRID IS 'Указатель на грид';
COMMENT ON COLUMN SYS_GRID_COLUMN.ID_COLUMN IS 'Указатель на колонку';
COMMENT ON COLUMN SYS_GRID_COLUMN.SORT_ORDER IS 'Порядок колонок';
COMMENT ON COLUMN SYS_GRID_COLUMN.WIDTH IS 'Ширина колонки';
COMMENT ON COLUMN SYS_GRID_COLUMN.VISIBLE IS 'Видимость колонки';
COMMENT ON COLUMN SYS_GRID_COLUMN.FOOT_FNC IS 'Агрегативная функция (Non = 0, Sum = 1, Avg = 2, Count = 3, FieldValue = 4, StaticText = 5)';
COMMIT;

------------------
-- SYS_GRID_EDIT
------------------

CREATE TABLE SYS_GRID_EDIT (
    ID_GRID             TFOREIGN,
    ID_COLUMN           TFOREIGN,
    SORT_ORDER          TINTEGER,
    CONTROL_TYPE        TSTRING,
    FIELD_WIDTH         TINTEGER,
    FIELD_HEIGHT        TINTEGER,
    FIELD_NEWL          TBOOLEAN2,
    FIELD_NEWT          TBOOLEAN2,
    LOOKUP_FIELD_VALUE  TSTRING,
    LOOKUP_LIST_KEY     TSTRING,
    LOOKUP_LIST_VALUE   TSTRING,
    LOOKUP_IID          TSTRING,
    LOOKUP_SQL          TSTRING,
    LOOKUP_SQL_NAME     TSTRING,
    LOOKUP_SQL_MASTER   TSTRING,
    CLONE_ABLE          TBOOLEAN2,
    REQUIRED            TBOOLEAN2,
    VISIBLE             TBOOLEAN2
);
COMMIT;

ALTER TABLE SYS_GRID_EDIT ADD CONSTRAINT SYS_GRID_EDIT$ID_COLUMN FOREIGN KEY (ID_COLUMN) REFERENCES SYS_COLUMN (ID) ON DELETE CASCADE;
ALTER TABLE SYS_GRID_EDIT ADD CONSTRAINT SYS_GRID_EDIT$ID_GRID FOREIGN KEY (ID_GRID) REFERENCES SYS_GRID (ID) ON DELETE CASCADE;
COMMIT;

COMMENT ON TABLE SYS_GRID_EDIT IS 'Связка гридов и колонок для системы автоматической настройки полей редактирования';
COMMENT ON COLUMN SYS_GRID_EDIT.ID_GRID IS 'Указатель на грид';
COMMENT ON COLUMN SYS_GRID_EDIT.ID_COLUMN IS 'Указатель на поле';
COMMENT ON COLUMN SYS_GRID_EDIT.SORT_ORDER IS 'Порядок полей';
COMMENT ON COLUMN SYS_GRID_EDIT.CONTROL_TYPE IS 'Тип контрола';
COMMENT ON COLUMN SYS_GRID_EDIT.FIELD_WIDTH IS 'Штрина контрола';
COMMENT ON COLUMN SYS_GRID_EDIT.FIELD_HEIGHT IS 'Высота контрола';
COMMENT ON COLUMN SYS_GRID_EDIT.FIELD_NEWL IS 'Позиционировать ли контрол на новой колонке';
COMMENT ON COLUMN SYS_GRID_EDIT.FIELD_NEWT IS 'Позиционировать ли контрол на новом рядке';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_FIELD_VALUE IS 'Значение лукапног ополя';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_LIST_KEY IS 'Ключевое поле списка лукапа';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_LIST_VALUE IS 'Поле значение списка лукапа';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_IID IS 'GUID компонента для октрытия лукапа';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_SQL IS 'SQL для выпадающего списка';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_SQL_NAME IS 'Имя SQL выпадающего списка';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_SQL_MASTER IS 'Имя мастера для SQL выпадающего списка';
COMMENT ON COLUMN SYS_GRID_EDIT.CLONE_ABLE IS 'Использовать поле при крпировании данных';
COMMENT ON COLUMN SYS_GRID_EDIT.REQUIRED IS 'Обязательное поле';
COMMENT ON COLUMN SYS_GRID_EDIT.VISIBLE IS 'Видимость контрола';
COMMIT;
