--------------------
-- DOMAINs
--------------------

CREATE DOMAIN TSTRING4K   AS VARCHAR(4096) CHARACTER SET WIN1251 DEFAULT '' NOT NULL COLLATE WIN1251_UA;
CREATE DOMAIN TSTRINGLONG AS VARCHAR(1024) CHARACTER SET WIN1251 DEFAULT '' NOT NULL COLLATE WIN1251_UA;
CREATE DOMAIN TMONEY      AS DECIMAL(10,2) DEFAULT 0 NOT NULL;
COMMIT;

COMMENT ON DOMAIN TSTRING4K IS 'varchar(4096) win1251_ua not null ''''';
COMMENT ON DOMAIN TSTRINGLONG IS 'Домен для длинных строк. Все что больше - уже блобы.';
COMMENT ON DOMAIN TTEXT IS 'Домен для больших текстовых';
COMMIT;

--------------------
-- UDFs
--------------------

DECLARE EXTERNAL FUNCTION UDF_GUID_SHA RETURNS BIGINT BY VALUE ENTRY_POINT 'UDF_GUID_SHA' MODULE_NAME 'mdo_udfs';
COMMIT;
COMMENT ON EXTERNAL FUNCTION UDF_GUID_SHA IS 'Функция получения GUID в целочисленном виде (квазихеширование алгоритмом SHA-1)';
COMMIT;

DECLARE EXTERNAL FUNCTION UDF_UAHTOSTR DOUBLE PRECISION, CSTRING(1024) RETURNS PARAMETER 2 ENTRY_POINT 'UDF_UAHTOSTR' MODULE_NAME 'mdo_udfs';
COMMIT;
COMMENT ON EXTERNAL FUNCTION UDF_UAHTOSTR IS 'Функция возвращает денежную сумму прописью';
COMMIT;

--------------------
-- EXCEPTIONs
--------------------

CREATE EXCEPTION EX_CUSTOM 'ЭТОТ ТЕКСТ СООБЩЕНИЯ ДОЛЖЕН БЫТЬ ПЕРЕОПРЕДЕЛЕН РАЗРАБОТЧИКОМ.';

--------------------
-- SYS_LANG_RESOURCE
--------------------

CREATE TABLE SYS_LANG_RESOURCE (
  ID        TPRIMARY,
  NAME_KEY  TSTRING,
  VALUE_UA  TSTRING4K,
  VALUE_RU  TSTRING4K,
  VALUE_EN  TSTRING4K,
  USER_TIME TDATETIME,
  VALUE_CUR COMPUTED BY (VALUE_RU)
);
COMMIT;

ALTER TABLE SYS_LANG_RESOURCE ADD CONSTRAINT SYS_LANG_RESOURCE$ID PRIMARY KEY (ID);
CREATE INDEX SYS_LANG_RESOURCE$KEY ON SYS_LANG_RESOURCE COMPUTED BY (UPPER(NAME_KEY));

COMMIT;

-----------
-- SYS_GRID
-----------

CREATE TABLE SYS_GRID (
    ID    TPRIMARY,
    IID   TSTRING,
    NAME  TSTRING
);
COMMIT;

ALTER TABLE SYS_GRID ADD CONSTRAINT SYS_GRID$ID PRIMARY KEY (ID);
CREATE UNIQUE INDEX SYS_GRID$IID ON SYS_GRID (IID);
COMMIT;

COMMENT ON TABLE SYS_GRID IS 'Справочник гридов для системы автоматической настройки колонок';
COMMENT ON COLUMN SYS_GRID.IID  IS 'GUID грида. Константой прописана на клиенте';
COMMENT ON COLUMN SYS_GRID.NAME IS 'Наименование грида';
COMMIT;

-------------
-- SYS_COLUMN
-------------

CREATE TABLE SYS_COLUMN (
    ID        TPRIMARY,
    FIELD     TSTRING,
    TITLE     TSTRING,
    LABEL     TSTRING,
    CHECKBOX  TBOOLEAN2
);
COMMIT;

ALTER TABLE SYS_COLUMN ADD CONSTRAINT SYS_COLUMN$ID PRIMARY KEY (ID);
COMMIT;

COMMENT ON TABLE SYS_COLUMN IS 'Справочник колонок для системы автоматической настройки колонок';
COMMENT ON COLUMN SYS_COLUMN.FIELD IS 'Наименование поля';
COMMENT ON COLUMN SYS_COLUMN.TITLE IS 'Заголовок группы колонок';
COMMENT ON COLUMN SYS_COLUMN.LABEL IS 'Заголовок колоноки';
COMMENT ON COLUMN SYS_COLUMN.CHECKBOX IS 'Отображать значение как чекбокс';
COMMIT;

------------------
-- SYS_GRID_COLUMN
------------------

CREATE TABLE SYS_GRID_COLUMN (
    ID_GRID     TFOREIGN,
    ID_COLUMN   TFOREIGN,
    SORT_ORDER  TINTEGER,
    WIDTH       TINTEGER,
    VISIBLE     TBOOLEAN2,
    FOOT_FNC    TENUM
);
COMMIT;

ALTER TABLE SYS_GRID_COLUMN ADD CONSTRAINT SYS_GRID_COLUMN$ID_COLUMN FOREIGN KEY (ID_COLUMN) REFERENCES SYS_COLUMN (ID) ON DELETE CASCADE;
ALTER TABLE SYS_GRID_COLUMN ADD CONSTRAINT SYS_GRID_COLUMN$ID_GRID FOREIGN KEY (ID_GRID) REFERENCES SYS_GRID (ID) ON DELETE CASCADE;
COMMIT;

COMMENT ON TABLE SYS_GRID_COLUMN IS 'Связка гридов и колонок для системы автоматической настройки колонок';
COMMENT ON COLUMN SYS_GRID_COLUMN.ID_GRID IS 'Указатель на грид';
COMMENT ON COLUMN SYS_GRID_COLUMN.ID_COLUMN IS 'Указатель на колонку';
COMMENT ON COLUMN SYS_GRID_COLUMN.SORT_ORDER IS 'Порядок колонок';
COMMENT ON COLUMN SYS_GRID_COLUMN.WIDTH IS 'Ширина колонки';
COMMENT ON COLUMN SYS_GRID_COLUMN.VISIBLE IS 'Видимость колонки';
COMMENT ON COLUMN SYS_GRID_COLUMN.FOOT_FNC IS 'Агрегативная функция (Non = 0, Sum = 1, Avg = 2, Count = 3, FieldValue = 4, StaticText = 5)';
COMMIT;

------------------
-- SYS_GRID_EDIT
------------------

CREATE TABLE SYS_GRID_EDIT (
    ID_GRID             TFOREIGN,
    ID_COLUMN           TFOREIGN,
    SORT_ORDER          TINTEGER,
    CONTROL_TYPE        TSTRING,
    FIELD_WIDTH         TINTEGER,
    FIELD_HEIGHT        TINTEGER,
    FIELD_NEWL          TBOOLEAN2,
    FIELD_NEWT          TBOOLEAN2,
    LOOKUP_FIELD_VALUE  TSTRING,
    LOOKUP_LIST_KEY     TSTRING,
    LOOKUP_LIST_VALUE   TSTRING,
    LOOKUP_IID          TSTRING,
    LOOKUP_SQL          TSTRING,
    LOOKUP_SQL_NAME     TSTRING,
    LOOKUP_SQL_MASTER   TSTRING,
    CLONE_ABLE          TBOOLEAN2,
    REQUIRED            TBOOLEAN2,
    VISIBLE             TBOOLEAN2
);
COMMIT;

ALTER TABLE SYS_GRID_EDIT ADD CONSTRAINT SYS_GRID_EDIT$ID_COLUMN FOREIGN KEY (ID_COLUMN) REFERENCES SYS_COLUMN (ID) ON DELETE CASCADE;
ALTER TABLE SYS_GRID_EDIT ADD CONSTRAINT SYS_GRID_EDIT$ID_GRID FOREIGN KEY (ID_GRID) REFERENCES SYS_GRID (ID) ON DELETE CASCADE;
COMMIT;

COMMENT ON TABLE SYS_GRID_EDIT IS 'Связка гридов и колонок для системы автоматической настройки полей редактирования';
COMMENT ON COLUMN SYS_GRID_EDIT.ID_GRID IS 'Указатель на грид';
COMMENT ON COLUMN SYS_GRID_EDIT.ID_COLUMN IS 'Указатель на поле';
COMMENT ON COLUMN SYS_GRID_EDIT.SORT_ORDER IS 'Порядок полей';
COMMENT ON COLUMN SYS_GRID_EDIT.CONTROL_TYPE IS 'Тип контрола';
COMMENT ON COLUMN SYS_GRID_EDIT.FIELD_WIDTH IS 'Штрина контрола';
COMMENT ON COLUMN SYS_GRID_EDIT.FIELD_HEIGHT IS 'Высота контрола';
COMMENT ON COLUMN SYS_GRID_EDIT.FIELD_NEWL IS 'Позиционировать ли контрол на новой колонке';
COMMENT ON COLUMN SYS_GRID_EDIT.FIELD_NEWT IS 'Позиционировать ли контрол на новом рядке';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_FIELD_VALUE IS 'Значение лукапног ополя';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_LIST_KEY IS 'Ключевое поле списка лукапа';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_LIST_VALUE IS 'Поле значение списка лукапа';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_IID IS 'GUID компонента для октрытия лукапа';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_SQL IS 'SQL для выпадающего списка';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_SQL_NAME IS 'Имя SQL выпадающего списка';
COMMENT ON COLUMN SYS_GRID_EDIT.LOOKUP_SQL_MASTER IS 'Имя мастера для SQL выпадающего списка';
COMMENT ON COLUMN SYS_GRID_EDIT.CLONE_ABLE IS 'Использовать поле при крпировании данных';
COMMENT ON COLUMN SYS_GRID_EDIT.REQUIRED IS 'Обязательное поле';
COMMENT ON COLUMN SYS_GRID_EDIT.VISIBLE IS 'Видимость контрола';
COMMIT;

-----------
-- C_OVS
-----------

CREATE TABLE C_OVS (
    ID    TPRIMARY,
    CODE  TSTRING,
    NAME  TSTRING
);
COMMIT;

ALTER TABLE C_OVS ADD CONSTRAINT C_OVS$ID PRIMARY KEY (ID);
COMMIT;

COMMENT ON TABLE C_OVS IS 'Справочник ОВС';
COMMIT;

-----------
-- AP_PHOTO_FOLDER
-----------

CREATE TABLE AP_PHOTO_FOLDER (
    ID           TSTRING,
    FOLDER       TSTRING,
    ADRESS       TSTRING,
    DEVICE_NAME  TSTRING,
    DEVICE_CODE  TSTRING,
    DEVICE_DATE  TDATETIME
);
COMMIT;

ALTER TABLE AP_PHOTO_FOLDER ADD CONSTRAINT AP_PHOTO_FOLDER$ID PRIMARY KEY (ID);
COMMIT;

-----------
-- TR_APPLICATIONS
-----------

CREATE TABLE TR_APPLICATIONS (
   ID          TINTEGER
  ,APP_NUMBER  TSTRING
  ,APP_DATE    TDATETIME
  ,MARK        TSTRING
  ,MODEL       TSTRING
  ,DNZ_NUMBER  TSTRING
  ,LAST_NAME   TSTRING
  ,FIRST_NAME  TSTRING
  ,MIDDLE_NAME TSTRING
  ,PASS_NO     TSTRING
  ,BIRTHDAY    TDATETIME
  ,BIRTH_PLACE TSTRING
  ,REGION_ID   TSTRING
  ,STREET_NAME TSTRING
  ,HOUSE_NO    TSTRING
  ,BUILDING_NO TSTRING
  ,FLAT_NO     TSTRING
);
COMMIT;

ALTER TABLE TR_APPLICATIONS ADD CONSTRAINT TR_APPLICATIONS$ID PRIMARY KEY (ID);
COMMIT;

-----------
-- AP_PHOTO_DECISION
-----------
CREATE SEQUENCE SEQ_PHOTO_DECISION;
ALTER SEQUENCE SEQ_PHOTO_DECISION RESTART WITH 1;
-----------
CREATE TABLE AP_PHOTO_DECISION (
   ID                TINTEGER
  ,ID_APP            TINTEGER
  ,NUMBER            TSTRING
  ,PHOTO             TBINARY
  -- DECISION
  ,DECISION_DATE     TDATETIME
  ,INSPECTOR_ID      TSTRING
  ,OVS_CODE          TSTRING
  -- VIOLATION
  ,VIOLATION_DATE    TDATETIME
  ,VIOLATION_PLACE   TSTRING
  ,TRAFFIC_SIGN      TSTRING
  ,ROADRULE_NO       TSTRING
  ,ARTICLE_NO        TSTRING
  ,LIMIT_SPEED       TINTEGER
  ,ACTUAL_SPEED      TINTEGER
  ,PENALTY           TMONEY
  -- APPLICATION
  ,MARK              TSTRING
  ,MODEL             TSTRING
  ,DNZ_NUMBER        TSTRING
  ,LAST_NAME         TSTRING
  ,FIRST_NAME        TSTRING
  ,MIDDLE_NAME       TSTRING
  ,PASS_NO           TSTRING
  ,BIRTHDAY          TDATETIME
  ,BIRTH_PLACE       TSTRING
  ,REGION_ID         TSTRING
  ,STREET_NAME       TSTRING
  ,HOUSE_NO          TSTRING
  ,BUILDING_NO       TSTRING
  ,FLAT_NO           TSTRING
  -- DEVICE
  ,DEVICE_NAME       TSTRING
  ,DEVICE_NO         TSTRING
  ,DEVICE_VALID_DATE TDATETIME
  -- PAYMENT
  ,RECIPIENT_NAME    TSTRING
  ,RECIPIENT_OKPO    TSTRING
  ,BANK_MFO          TSTRING
  ,BANK_ACCOUNT      TSTRING
  -- BREACH
  ,BREACH_ID         TSTRING
);
COMMIT;

ALTER TABLE AP_PHOTO_DECISION ADD CONSTRAINT AP_PHOTO_DECISION$ID PRIMARY KEY (ID);
COMMIT;

