SET TERM ^;

CREATE OR ALTER PROCEDURE ADD_SYS_GRID(
   IID  TSTRING
  ,NAME TSTRING
)
RETURNS (
  ID TINTEGER
  )
AS
BEGIN
  SELECT ID
  FROM SYS_GRID
  WHERE IID = :IID
  INTO :ID;

  IF (COALESCE(:ID, 0) = 0) THEN
    INSERT INTO SYS_GRID (ID, IID, NAME)
    VALUES (UDF_GUID_SHA(),:IID,:NAME)
    RETURNING ID INTO :ID;

  SUSPEND;
END
^

SET TERM ;^
