SET TERM ^;

CREATE OR ALTER PROCEDURE ADD_SYS_GRID_COLUMN(
   ID_GRID    TINTEGER
  ,SORT_ORDER TINTEGER
  ,FIELD      TSTRING
  ,TITLE      TSTRING
  ,LABEL      TSTRING
  ,WIDTH      TINTEGER
  ,CHECKBOX   TBOOLEAN2
  ,VISIBLE    TBOOLEAN2
  ,FOOT_FNC   TENUM -- Non = 0, Sum = 1, Avg = 2, Count = 3, FieldValue = 4, StaticText = 5
)
AS
  DECLARE ID TYPE OF TINTEGER;
BEGIN
  SELECT ID FROM ADD_SYS_COLUMN(:FIELD,:TITLE,:LABEL,:CHECKBOX) INTO :ID;

  IF (NOT EXISTS(SELECT 1 FROM SYS_GRID_COLUMN WHERE ID_GRID = :ID_GRID AND ID_COLUMN = :ID)) THEN
    INSERT INTO SYS_GRID_COLUMN (ID_GRID,ID_COLUMN,SORT_ORDER,WIDTH,VISIBLE,FOOT_FNC)
    VALUES (:ID_GRID,:ID,:SORT_ORDER,:WIDTH,:VISIBLE,:FOOT_FNC);
  ELSE
    UPDATE SYS_GRID_COLUMN SET
       SORT_ORDER = :SORT_ORDER
      ,WIDTH      = :WIDTH
      ,VISIBLE    = :VISIBLE
      ,FOOT_FNC   = :FOOT_FNC
    WHERE ID_GRID   = :ID_GRID
      AND ID_COLUMN = :ID;

END
^

SET TERM ;^
