SET TERM ^;

CREATE OR ALTER PROCEDURE ADD_SYS_GRID_EDIT_2(
   ID_GRID      TINTEGER
  ,SORT_ORDER   TINTEGER
  ,FIELD        TSTRING
  ,LABEL        TSTRING
  ,CONTROL_TYPE TSTRING
  ,VISIBLE      TBOOLEAN2
  ,REQUIRED     TBOOLEAN2
  ,CLONE_ABLE   TBOOLEAN2
  ,WIDTH        TINTEGER = 0

  ,LOOKUP_FIELD_VALUE TSTRING = ''
  ,LOOKUP_LIST_KEY    TSTRING = ''
  ,LOOKUP_LIST_VALUE  TSTRING = ''
  ,LOOKUP_IID         TSTRING = ''
  ,LOOKUP_SQL         TSTRING = ''
  ,LOOKUP_SQL_NAME    TSTRING = ''
  ,LOOKUP_SQL_MASTER  TSTRING = ''
)
AS
  DECLARE ID_COLUMN TYPE OF TINTEGER;
BEGIN
  SELECT ID FROM ADD_SYS_COLUMN_2(:FIELD,:LABEL) INTO :ID_COLUMN;

  IF (:LOOKUP_SQL_NAME = '') THEN
    LOOKUP_SQL_NAME = :LOOKUP_SQL;

  DELETE FROM SYS_GRID_EDIT WHERE ID_GRID = :ID_GRID AND ID_COLUMN = :ID_COLUMN;

  INSERT INTO SYS_GRID_EDIT (
    ID_GRID, ID_COLUMN, SORT_ORDER, CONTROL_TYPE, VISIBLE, CLONE_ABLE, REQUIRED,
    LOOKUP_FIELD_VALUE, LOOKUP_LIST_KEY, LOOKUP_LIST_VALUE, LOOKUP_IID, LOOKUP_SQL, LOOKUP_SQL_NAME, LOOKUP_SQL_MASTER,
    FIELD_WIDTH, FIELD_HEIGHT, FIELD_NEWL, FIELD_NEWT)
  VALUES (
    :ID_GRID,:ID_COLUMN,:SORT_ORDER,:CONTROL_TYPE,:VISIBLE,:CLONE_ABLE,:REQUIRED,
    :LOOKUP_FIELD_VALUE,:LOOKUP_LIST_KEY,:LOOKUP_LIST_VALUE,:LOOKUP_IID,:LOOKUP_SQL,:LOOKUP_SQL_NAME,:LOOKUP_SQL_MASTER,
    :WIDTH, 0, 0, 0);

END
^

SET TERM ;^
