SET TERM ^ ;

CREATE OR ALTER PROCEDURE ADD_SYS_COLUMN (
    FIELD    TSTRING,
    TITLE    TSTRING,
    LABEL    TSTRING,
    CHECKBOX TBOOLEAN2)
RETURNS (
    ID TINTEGER)
AS
  declare variable V_TITLE TYPE OF TSTRING;
  declare variable V_LABEL TYPE OF TSTRING;
BEGIN

  SELECT /*FIRST 1*/ ID
  FROM SYS_COLUMN
  WHERE FIELD = :FIELD
    AND TITLE = :TITLE
    AND LABEL = :LABEL
    AND CHECKBOX = :CHECKBOX
  INTO :ID;

  IF (COALESCE(:ID, 0) = 0) THEN
    INSERT INTO SYS_COLUMN (ID, FIELD, TITLE, LABEL, CHECKBOX)
    VALUES (UDF_GUID_SHA(),:FIELD,:TITLE,:LABEL,:CHECKBOX)
    RETURNING ID INTO :ID;

   SUSPEND;
END^

SET TERM ; ^

