SET TERM ^;

CREATE OR ALTER PROCEDURE AP_PHOTO_FOLDER$GET
RETURNS (
  ID           TSTRING,
  FOLDER       TSTRING,
  ADRESS       TSTRING,
  DEVICE       TSTRING,
  DEVICE_NAME  TSTRING,
  DEVICE_CODE  TSTRING,
  DEVICE_DATE  TDATETIME
  )
AS
BEGIN
  SELECT
     ID
    ,FOLDER
    ,ADRESS
    ,DEVICE_NAME
    ,DEVICE_CODE
    ,DEVICE_DATE
  FROM AP_PHOTO_FOLDER
  WHERE ID = UPPER(CURRENT_USER)
  INTO
     :ID
    ,:FOLDER
    ,:ADRESS
    ,:DEVICE_NAME
    ,:DEVICE_CODE
    ,:DEVICE_DATE;

  IF (ROW_COUNT = 0) THEN
  BEGIN
    ID           = UPPER(CURRENT_USER);
    FOLDER       = '';
    ADRESS       = '';
    DEVICE       = '';
    DEVICE_NAME  = '';
    DEVICE_CODE  = '';
    DEVICE_DATE  = NULL;
  END ELSE
    DEVICE = DEVICE_NAME || ' ¹ ' || DEVICE_CODE;

  SUSPEND;
END^

SET TERM ;^
