SET TERM ^;

CREATE OR ALTER PROCEDURE AP_PHOTO_FOLDER$UPD(
  FOLDER       TSTRING,
  ADRESS       TSTRING,
  DEVICE_NAME  TSTRING,
  DEVICE_CODE  TSTRING,
  DEVICE_DATE  TDATETIME
  )
AS
BEGIN

  UPDATE OR INSERT INTO AP_PHOTO_FOLDER (
     ID
    ,FOLDER
    ,ADRESS
    ,DEVICE_NAME
    ,DEVICE_CODE
    ,DEVICE_DATE
  ) VALUES (
     UPPER(CURRENT_USER)
    ,:FOLDER
    ,:ADRESS
    ,:DEVICE_NAME
    ,:DEVICE_CODE
    ,:DEVICE_DATE
  );

  SUSPEND;
END^

SET TERM ;^
