SET TERM ^;

CREATE OR ALTER PROCEDURE AP_PHOTO_DECISION$FIND_ROW(
  A_PHOTO_DECISION_ID TINTEGER
  )
RETURNS (
   PHOTO_DECISION_ID TINTEGER
  ,NUMBER            TSTRING
  ,DECISION_DATE     TDATETIME
  ,INSPECTOR_NAME    TSTRING
  ,OVS_NAME          TSTRING
  ,VIOLATION_DATE    TDATETIME
  ,VIOLATION_PLACE   TSTRING
  ,MARK              TSTRING
  ,MODEL             TSTRING
  ,DNZ_NUMBER        TSTRING
  ,VIOLATOR          TSTRING
  ,ACTUAL_SPEED      TINTEGER
  ,LIMIT_SPEED       TINTEGER
  )
AS
  DECLARE V_SQL TTEXT;
BEGIN

  V_SQL = '
    SELECT
       D.ID
      ,D.DECISION_DATE
      ,D.NUMBER
      ,D.INSPECTOR_ID
      ,OVS.NAME
      ,D.VIOLATION_DATE
      ,D.VIOLATION_PLACE
      ,D.MARK
      ,D.MODEL
      ,D.DNZ_NUMBER
      ,D.LAST_NAME || '' '' || D.FIRST_NAME || COALESCE('' '' || D.MIDDLE_NAME, '''')
      ,D.ACTUAL_SPEED
      ,D.LIMIT_SPEED
    FROM AP_PHOTO_DECISION D
      LEFT JOIN C_OVS OVS ON OVS.CODE = D.OVS_CODE
    WHERE D.ID = ' || :A_PHOTO_DECISION_ID;

  FOR
    EXECUTE STATEMENT (:V_SQL)
    INTO
       :PHOTO_DECISION_ID
      ,:DECISION_DATE
      ,:NUMBER
      ,:INSPECTOR_NAME
      ,:OVS_NAME
      ,:VIOLATION_DATE
      ,:VIOLATION_PLACE
      ,:MARK
      ,:MODEL
      ,:DNZ_NUMBER
      ,:VIOLATOR
      ,:ACTUAL_SPEED
      ,:LIMIT_SPEED
  DO
    SUSPEND;

END^

SET TERM ;^
