SET TERM ^ ;

CREATE OR ALTER PROCEDURE SYS_LANG_RESOURCE$INS (
    A_NAME_KEY     TYPE OF COLUMN SYS_LANG_RESOURCE.NAME_KEY,
    A_VALUE_UA     TYPE OF COLUMN SYS_LANG_RESOURCE.VALUE_UA,
    A_VALUE_RU     TYPE OF COLUMN SYS_LANG_RESOURCE.VALUE_RU,
    A_VALUE_EN     TYPE OF COLUMN SYS_LANG_RESOURCE.VALUE_EN)
AS
  DECLARE V_ID TYPE OF TINTEGER;
BEGIN
  SELECT ID FROM SYS_LANG_RESOURCE WHERE NAME_KEY = :A_NAME_KEY INTO :V_ID;
  V_ID = COALESCE(:V_ID, UDF_GUID_SHA());

  UPDATE OR INSERT INTO SYS_LANG_RESOURCE (ID, NAME_KEY, VALUE_UA, VALUE_RU, VALUE_EN, USER_TIME)
  VALUES (:V_ID, :A_NAME_KEY, :A_VALUE_UA, :A_VALUE_RU, :A_VALUE_EN, CURRENT_TIMESTAMP);

END^

SET TERM ; ^

COMMENT ON PROCEDURE SYS_LANG_RESOURCE$INS IS 'Вставка записей в SYS_LANG_RESOURCE
При заданных A_ID_DICT и ID_DICT_ITEM пытается создать связь SYS_DICT_ITEM.ID_LANG_RES - SYS_LANG_RESOURCE.ID';

