/******************************************************************************/
/***          Generated by IBExpert 2012.11.27 14.07.2015 12:15:16          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;

SET CLIENTLIB '..\bin\fbclient.dll';

CREATE DATABASE '..\fdb\mdo.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1251 COLLATION WIN1251;

/******************************************************************************/
/***                                Domains                                 ***/
/******************************************************************************/

CREATE DOMAIN TBINARY AS
BLOB SUB_TYPE 0 SEGMENT SIZE 100
DEFAULT 0
NOT NULL;

CREATE DOMAIN TBOOLEAN AS
BIGINT
DEFAULT 0
NOT NULL
CHECK (VALUE BETWEEN 0 AND 1);

CREATE DOMAIN TBOOLEAN2 AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK (VALUE BETWEEN 0 AND 1);

CREATE DOMAIN TDATE AS
DATE;

CREATE DOMAIN TDATETIME AS
TIMESTAMP;

CREATE DOMAIN TDOUBLE AS
DOUBLE PRECISION
DEFAULT 0
NOT NULL;

CREATE DOMAIN TENUM AS
SMALLINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN TFOREIGN AS
BIGINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN TINTEGER AS
BIGINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN TPRIMARY AS
BIGINT
NOT NULL;

CREATE DOMAIN TSTRING AS
VARCHAR(255)
DEFAULT ''
NOT NULL
COLLATE WIN1251_UA;

CREATE DOMAIN TTEXT AS
BLOB SUB_TYPE 1 SEGMENT SIZE 100
DEFAULT ''
NOT NULL;

CREATE DOMAIN TTIME AS
TIME;

CREATE DOMAIN TUID AS
VARCHAR(38)
DEFAULT ''
NOT NULL;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR SEQ_PRIMARY;
SET GENERATOR SEQ_PRIMARY TO 0;



SET TERM ^ ; 



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

CREATE PROCEDURE SYS_SET_PRIVILEGES
AS
BEGIN
  EXIT;
END^





CREATE PROCEDURE SYS_SET_STATISTICS
AS
BEGIN
  EXIT;
END^






SET TERM ; ^



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE SYS_VER (
    ID           TPRIMARY,
    ID_VER_SYNC  TINTEGER,
    VER_APP      TSTRING,
    USER_NOTE    TSTRING,
    USER_NAME    TSTRING,
    USER_TIME    TDATETIME
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE SYS_VER ADD CONSTRAINT SYS_VER$ID PRIMARY KEY (ID);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE DESCENDING INDEX SYS_VER$ID_DESC ON SYS_VER (ID);


/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE SYS_SET_PRIVILEGES
AS
  DECLARE VARIABLE V_NAME TSTRING;
BEGIN
  FOR
    SELECT RDB$RELATION_NAME FROM RDB$RELATIONS WHERE COALESCE(RDB$SYSTEM_FLAG, 1) <> 1
    INTO :V_NAME
  DO
    EXECUTE STATEMENT 'GRANT ALL ON TABLE '||TRIM(:V_NAME)||' TO PUBLIC';

  FOR
    SELECT RDB$PROCEDURE_NAME FROM RDB$PROCEDURES WHERE COALESCE(RDB$SYSTEM_FLAG, 1) <> 1
    INTO :V_NAME
  DO
    EXECUTE STATEMENT 'GRANT EXECUTE ON PROCEDURE '||TRIM(:V_NAME)||' TO PUBLIC';
END^


ALTER PROCEDURE SYS_SET_STATISTICS
AS
  DECLARE VARIABLE V_NAME VARCHAR(31);
BEGIN
  FOR
    SELECT
      RDB$INDEX_NAME
    FROM RDB$INDICES
    INTO
      :V_NAME
  DO
    EXECUTE STATEMENT 'SET STATISTICS INDEX '||:V_NAME;
END^



SET TERM ; ^


/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

DESCRIBE PROCEDURE SYS_SET_PRIVILEGES
'”станавливает все права дл€ всех. Ќеобходима дл€ автоматической расдачи прав дл€ всех на новые метаданные. Ќа насто€щее врем€ мы не геммороимс€ с системой прав доступа к базе данных.';

DESCRIBE PROCEDURE SYS_SET_STATISTICS
'ѕересчет статистики всех индексов в базе';
